Change indent to tabs, micro optimisation

diff --git a/blackhole b/blackhole
--- a/blackhole
+++ b/blackhole
@@ -1,72 +1,72 @@
-#!/usr/bin/env bash
-# Written by: predatorfreak
+#!/usr/bin/env	bash
+#	Written by: predatorfreak
 
-# Environment checks.
+#	Environment checks.
 if [ ! `whoami` = "root" ]; then
- echo "Blackhole requires root privilages to modify iptables rules."
- exit 1
+	echo "Blackhole requires root privilages to modify iptables rules."
+	exit 1
 fi
 
 if [ -f /etc/blackhole/blackhole.conf ]; then
- . /etc/blackhole/blackhole.conf
- export CONFDIR=/etc/blackhole
+	. /etc/blackhole/blackhole.conf
+	export CONFDIR=/etc/blackhole
 elif [ -f $PWD/config/blackhole.conf ]; then
- . $PWD/config/blackhole.conf
- export CONFDIR=$PWD/config
+	. $PWD/config/blackhole.conf
+	export CONFDIR=$PWD/config
 else
- echo "Couldn't find configuration file, dieing."
- exit 1
+	echo "Couldn't find configuration file, dieing."
+	exit 1
 fi
 
-if [ -d $PREFIX/share/blackhole/modules ] && [ -f $PREFIX/share/blackhole/modules/core.bmod ]; then
- MODDIR=$PREFIX/share/blackhole/modules
-elif [ -d $PWD/modules ] && [ -f $PWD/modules/core.bmod ]; then
- MODDIR=$PWD/modules
+if [ -d $PREFIX/share/blackhole/modules -a -f $PREFIX/share/blackhole/modules/core.bmod ]; then
+	MODDIR=$PREFIX/share/blackhole/modules
+elif [ -d $PWD/modules -a -f $PWD/modules/core.bmod ]; then
+	MODDIR=$PWD/modules
 else
- echo "Modules directory doesn't exist, dieing."
- exit 1
+	echo "Modules directory doesn't exist, dieing."
+	exit 1
 fi
 
 if [ -f $PREFIX/share/blackhole/includes/module-functions ]; then
- . $PREFIX/share/blackhole/includes/module-functions
+	. $PREFIX/share/blackhole/includes/module-functions
 elif [ -f $PWD/includes/module-functions ]; then
- . $PWD/includes/module-functions
+	. $PWD/includes/module-functions
 else
- echo "Couldn't find the requried includes, dieing."
- exit 1
+	echo "Couldn't find the requried includes, dieing."
+	exit 1
 fi
 
 case "$1" in
 start)
-if [ $LOG_DROPPED_PACKETS = "YES" ]; then
- iptables -N LOG_DROP
- iptables -A LOG_DROP -j LOG --log-tcp-options --log-ip-options --log-prefix $LOGPREFIX
- iptables -A LOG_DROP -j DROP
- export DROP=LOG_DROP
-else
- export DROP=DROP
-fi
+	if [ $LOG_DROPPED_PACKETS = "YES" ]; then
+		iptables -N LOG_DROP
+		iptables -A LOG_DROP -j LOG --log-tcp-options --log-ip-options --log-prefix $LOGPREFIX
+		iptables -A LOG_DROP -j DROP
+		export DROP=LOG_DROP
+	else
+		export DROP=DROP
+	fi
 
-if [ ! -z "${MODULES[*]}" ]; then
- echo "Setting iptables rules."
- echo -n "Loading blackhole modules: "
- for i in ${MODULES[@]}; do
-  load_module $i
-  LOADEDMODULES="$LOADEDMODULES $i"
- done
- echo
-fi
+	if [ -n "${MODULES[*]}" ]; then
+		echo "Setting iptables rules."
+		echo -n "Loading blackhole modules: "
+		for i in ${MODULES[@]}; do
+		 load_module $i
+		 LOADEDMODULES="$LOADEDMODULES $i"
+		done
+		echo
+	fi
 ;;
 stop)
-iptables -F
-iptables -P INPUT ACCEPT
-iptables -P FORWARD ACCEPT
-iptables -P OUTPUT ACCEPT
-iptables -X
+	iptables -F
+	iptables -P INPUT ACCEPT
+	iptables -P FORWARD ACCEPT
+	iptables -P OUTPUT ACCEPT
+	iptables -X
 ;;
 restart)
-$0 stop
-sleep 2
-$0 start
+	$0 stop
+	sleep 2
+	$0 start
 ;;
 esac
diff --git a/includes/functions b/includes/functions
--- a/includes/functions
+++ b/includes/functions
@@ -1,18 +1,18 @@
-# functions
-# Written by: predatorfreak
+#	functions
+#	Written by: predatorfreak
 
-failcheck() {
+failcheck()	{
 if [ $? = "1" ]; then
- echo "Program exited with an error, exiting."
- exit 1
+	echo "Program exited with an error, exiting."
+	exit 1
 elif [ $? = "2" ]; then
- echo "Program exited with status 2, exiting."
- exit 1
+	echo "Program exited with status 2, exiting."
+	exit 1
 elif [ $? = "130" ]; then
- echo "Program terminated by signal 2"
- exit 1
+	echo "Program terminated by signal 2"
+	exit 1
 elif [ $? = "137" ]; then
- echo "Program terminated by signal 9"
- exit 1
+	echo "Program terminated by signal 9"
+	exit 1
 fi
 }
diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -1,90 +1,90 @@
 #!/bin/sh
-# installer
-# Written by: predatorfreak
+#	installer
+#	Written by: predatorfreak
 
 if [ ! `whoami` = "root" ]; then
- echo "You must be root in order to install blackhole."
- exit 1
+	echo "You must be root in order to install blackhole."
+	exit 1
 fi
 
 if [ -f $PWD/config/installation.conf ] && [ -f $PWD/config/blackhole.conf ]; then
- if [ -f $PWD/includes/installation-functions ]; then
-  . $PWD/config/installation.conf
-  . $PWD/config/blackhole.conf
-  . $PWD/includes/installation-functions
- else
-  echo "Unable to load the required functions."
-  exit 1
- fi
+	if [ -f $PWD/includes/installation-functions ]; then
+		. $PWD/config/installation.conf
+		. $PWD/config/blackhole.conf
+		. $PWD/includes/installation-functions
+	else
+		echo "Unable to load the required functions."
+		exit 1
+	fi
 else
- echo "Unable to load the configuration file."
- exit 1
+	echo "Unable to load the configuration file."
+	exit 1
 fi
 
 case "$1" in
 slackware)
-if [ ! -d /etc/blackhole ]; then
- echo "Beginning Blackhole installation."
- rcins slackware
- createdirs
- cp config/{blackhole,extopts,ipblock}.conf /etc/blackhole/
- cp includes/{module-functions,functions} $PREFIX/share/blackhole/includes/
- cp modules/* $PREFIX/share/blackhole/modules/
- cp blackhole $PREFIX/bin/blackhole
- chmod +x $PREFIX/bin/blackhole
- applyrules
- echo "Done."
- exit 0
-else
- echo "Installer: The directory /etc/blackhole already exist, please run upgrader instead."
- exit 1
-fi
+	if [ ! -d /etc/blackhole ]; then
+		echo "Beginning Blackhole installation."
+		rcins slackware
+		createdirs
+		cp config/{blackhole,extopts,ipblock}.conf /etc/blackhole/
+		cp includes/{module-functions,functions} $PREFIX/share/blackhole/includes/
+		cp modules/* $PREFIX/share/blackhole/modules/
+		cp blackhole $PREFIX/bin/blackhole
+		chmod +x $PREFIX/bin/blackhole
+		applyrules
+		echo "Done."
+		exit 0
+	else
+		echo "Installer: The directory /etc/blackhole already exist, please run upgrader instead."
+		exit 1
+	fi
 ;;
 generic)
-if [ ! -d /etc/blackhole ]; then
- echo "Beginning Blackhole installation"
- createdirs
- cp config/{blackhole,extopts,ipblock}.conf /etc/blackhole/
- cp includes/{module-functions,functions} $PREFIX/share/blackhole/includes/
- cp modules/* $PREFIX/share/blackhole/modules/
- cp blackhole $PREFIX/bin/blackhole
- chmod +x $PREFIX/bin/blackhole
- applyrules 
- echo "Done."
- exit 0
-else
- echo "Installer: The directory /etc/blackhole already exist, please run upgrader instead."
- exit 1
-fi
+	if [ ! -d /etc/blackhole ]; then
+		echo "Beginning Blackhole installation"
+		createdirs
+		cp config/{blackhole,extopts,ipblock}.conf /etc/blackhole/
+		cp includes/{module-functions,functions} $PREFIX/share/blackhole/includes/
+		cp modules/* $PREFIX/share/blackhole/modules/
+		cp blackhole $PREFIX/bin/blackhole
+		chmod +x $PREFIX/bin/blackhole
+		applyrules 
+		echo "Done."
+		exit 0
+	else
+		echo "Installer: The directory /etc/blackhole already exist, please run upgrader instead."
+		exit 1
+	fi
 ;;
 crux)
-if [ ! -d /etc/blackhole ]; then
- echo "Beginning CRUX installation"
- rcins crux
- createdirs
- cp config/{blackhole,extopts,ipblock}.conf /etc/blackhole/
- cp includes/{module-functions,functions} $PREFIX/share/blackhole/includes/
- cp modules/* $PREFIX/share/blackhole/modules/
- cp blackhole $PREFIX/bin/blackhole
- chmod +x $PREFIX/bin/blackhole
- applyrules
- echo "Done"
- exit 0
-else
- echo "Installer: The directory /etc/blackhole already exist, please run upgrader instead."
- exit 1
-fi
+	if [ ! -d /etc/blackhole ]; then
+		echo "Beginning CRUX installation"
+		rcins crux
+		createdirs
+		cp config/{blackhole,extopts,ipblock}.conf /etc/blackhole/
+		cp includes/{module-functions,functions} $PREFIX/share/blackhole/includes/
+		cp modules/* $PREFIX/share/blackhole/modules/
+		cp blackhole $PREFIX/bin/blackhole
+		chmod +x $PREFIX/bin/blackhole
+		applyrules
+		echo "Done"
+		exit 0
+	else
+		echo "Installer: The directory /etc/blackhole already exist, please run upgrader instead."
+		exit 1
+	fi
 ;;
 *)
-echo "installer -"
-echo "A streamlined installation system for blackhole"
-echo
-echo "Usage: ./installer [OPTION]"
-echo
-echo "Options:"
-echo "slackware"
-echo "crux"
-echo "generic"
-exit 0
+	echo "installer -"
+	echo "A streamlined installation system for blackhole"
+	echo
+	echo "Usage: ./installer [OPTION]"
+	echo
+	echo "Options:"
+	echo "slackware"
+	echo "crux"
+	echo "generic"
+	exit 0
 ;;
 esac
