Massive installation overhaul to facilitate packaging, some cleanup work.

diff --git a/includes/functions b/includes/functions
--- a/includes/functions
+++ b/includes/functions
@@ -1,6 +1,15 @@
 # functions
 # Written by: predatorfreak
 
+die() {
+	echo "ERROR: $@"
+	exit 1
+}
+
+warn() {
+	echo "WARNING: $@"
+}
+
 failcheck()	{
 $@
 if [ $? = "1" ]; then
